message.date instead of datetime.utcnow()
rgit/CheckYourStats pull request #3
Opened 2020-12-27 12:50 UTC by Demenkop

2020-12-28 16:31 UTC, nm17 requested changes
`message.date` не tz-aware и не является tz-naive в поясе UTC. Найди способ как его перевести в UTC (пока что без разницы tz-naive на выходе или нет, т.к PonyORM сьедает tz инфу).

2020-12-29 18:01 UTC, Demenkop commented
так `message.date` и так уже в utc, чо тебе эщо надо?)))

2020-12-30 23:08 UTC, xcaq commented
Сорян пчел.... нужны изменения...)

2020-12-30 23:46 UTC, xcaq commented
@Demenkop @nm17 Читаем, просвещаемся https://stackoverflow.com/questions/79797/how-to-convert-local-time-string-to-utc

2020-12-31 04:10 UTC, nm17 commented
@Demenkop у меня он был не UTC вроде

2020-12-31 19:32 UTC, merged